// automatically generated by the FlatBuffers compiler, do not modify

package com.miti99.netty.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class LoginRequest extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static LoginRequest getRootAsLoginRequest(ByteBuffer _bb) { return getRootAsLoginRequest(_bb, new LoginRequest()); }
  public static LoginRequest getRootAsLoginRequest(ByteBuffer _bb, LoginRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public LoginRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int userId() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createLoginRequest(FlatBufferBuilder builder,
      int userId) {
    builder.startTable(1);
    LoginRequest.addUserId(builder, userId);
    return LoginRequest.endLoginRequest(builder);
  }

  public static void startLoginRequest(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addUserId(FlatBufferBuilder builder, int userId) { builder.addInt(0, userId, 0); }
  public static int endLoginRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public LoginRequest get(int j) { return get(new LoginRequest(), j); }
    public LoginRequest get(LoginRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

