// automatically generated by the FlatBuffers compiler, do not modify

package com.miti99.netty.fbs;

public final class PacketData {
  private PacketData() { }
  public static final byte NONE = 0;
  public static final byte LoginRequest = 1;
  public static final byte LoginResponse = 2;

  public static final String[] names = { "NONE", "LoginRequest", "LoginResponse", };

  public static String name(int e) { return names[e]; }
}

